### ISSUE TITLE
Support for Large Technic Motor (88013), e.g. for Lego Crocodile (10277)

### ISSUE THREAD

**Issue by Kinetize** [virantha/bricknil#26]
Hello!

Thanks for your good work with this repository!
Do you plan to add support for the large technic motor ([88013](https://www.lego.com/de-de/product/technic-large-motor-88013))? This could be e.g. useful to control the lego crocodile ([10277](https://www.lego.com/de-de/product/crocodile-locomotive-10277)).

**Comment by justxi** [comment]
Is that one https://github.com/virantha/bricknil/blob/a908b98938ee1028373186e31cb2d43c68f54b76/bricknil/sensor/motor.py#L296 what you are searching for?

**Comment by Kinetize** [comment]
That could indeed be it, I just didnt search in that place. Thank you!
